package data_access.factories.objects;

import data_access.factories.interfaces.DatabaseUserUpdatePasswordDataAccessObjectFactoryInterface;

public class DatabaseUserUpdatePasswordDataAccessObjectFactory implements DatabaseUserUpdatePasswordDataAccessObjectFactoryInterface {
}
