package data_access.factories.objects;

import data_access.factories.interfaces.DatabaseShoppingCartUpdateDeleteDataAccessObjectFactoryInterface;

public class DatabaseShoppingCartUpdateDeleteDataAccessObjectFactory implements DatabaseShoppingCartUpdateDeleteDataAccessObjectFactoryInterface {
}
