package data_access.factories.objects;

import data_access.factories.interfaces.DatabaseUserUpdateNameDataAccessObjectFactoryInterface;

public class DatabaseUserUpdateNameDataAccessObjectFactory implements DatabaseUserUpdateNameDataAccessObjectFactoryInterface {
}
