package data_access.factories.objects;

import data_access.factories.interfaces.DatabaseShoppingCartReadDataAccessObjectFactoryInterface;

public class DatabaseShoppingCartReadDataAccessObjectFactory implements DatabaseShoppingCartReadDataAccessObjectFactoryInterface {
}
