package data_access.factories.objects;

import data_access.factories.interfaces.DatabaseShoppingCartUpdateAddDataAccessObjectFactoryInterface;

public class DatabaseShoppingCartUpdateAddDataAccessObjectFactory implements DatabaseShoppingCartUpdateAddDataAccessObjectFactoryInterface {
}
