package data_access.objects.Product;

import data_access.interfaces.Prouct.ProductUpdateBuyerScheduleDataAccessInterface;

public class DatabaseProductUpdateBuyerScheduleDataAccessObject implements ProductUpdateBuyerScheduleDataAccessInterface {
}
