package data_access.objects.Product;

import data_access.interfaces.Prouct.ProductUpdateSellerScheduleDataAccessInterface;

public class DatabaseProductUpdateSellerScheduleDataAccessObject implements ProductUpdateSellerScheduleDataAccessInterface {
}
