package data_access.objects;

import data_access.factories.interfaces.DatabaseUserUpdateNameDataAccessObjectFactoryInterface;

public class DatabaseUserUpdateNameDataAccessObject implements DatabaseUserUpdateNameDataAccessObjectFactoryInterface {

}
